### ISSUE TITLE
Dependencies on Ubuntu 18.04

### ISSUE THREAD

**Issue by MitraMai** [sabinahofmann/homebank-gtk-app#1]
Hello hello!
Seems like a program that I could really make use of :)
But I'm having trouble with the dependencies. Don't really get which to install! I get this message when trying to run ./homebank-gtk:
`Traceback (most recent call last):
	2: from ./homebank-gtk:3:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- gtk3 (LoadError)
`
And I can't figure out which package to install. Could you please specify, if it's not to much work?

**Comment by sabinahofmann** [comment]
Hi, 
thank you to try the desktop app to convert csv for homebank. Have you installed the gem "gtk3" before? It is needed for the gui. I will highlight the note in the Readme better.

**Comment by MitraMai** [comment]
Hello! These are the packages I get listed when searching for gem and gtk3:
```[martin@MegaCityOne ~]$apt search gem gtk3
Sorterar… Färdig
Fulltextsökning… Färdig

golang-github-gotk3-gotk3-dev/bionic,bionic 0.0~GOTK3~0~2~0+git20170418.0.96d4110-2 all
  Go bindings for GTK3

homebank/bionic,now 5.2.3-0~66~ubuntu18.04.1 amd64 [installerat]
  Manage your personal accounts at home

homebank-data/bionic,bionic,now 5.2.3-0~66~ubuntu18.04.1 all [installerat,automatiskt]
  Data files for homebank

homebank-dbg/bionic 5.2.3-0~66~ubuntu18.04.1 amd64
  Debugginf symbols for homebank

packagekit-gtk3-module/bionic-updates 1.1.9-1ubuntu2.18.04.5 amd64
  Install fonts automatically using PackageKit

python-aptdaemon.gtk3widgets/bionic,bionic 1.1.1+bzr982-0ubuntu19 all
  Python 2 GTK+ 3 widgets to run an aptdaemon client

python3-aptdaemon.gtk3widgets/bionic,bionic,now 1.1.1+bzr982-0ubuntu19 all [installerat]
  Python 3 GTK+ 3 widgets to run an aptdaemon client

quodlibet/bionic,bionic 3.9.1-1.2 all
  audio library manager and player for GTK3

spacefm/bionic 1.0.5-2 amd64
  Multi-panel tabbed file manager - GTK2 version

spacefm-gtk3/bionic 1.0.5-2 amd64
  Multi-panel tabbed file manager - GTK3 version```

Can't figure out which one it is! And sorry for the formatting, don't know what I'm doing wrong here :)

**Comment by sabinahofmann** [comment]
So this is the error if the gem gtk3 is not installed.
```
bina@debianbina:~/code/homebank-gtk-app$ ./homebank-gtk 
Traceback (most recent call last):
	2: from ./homebank-gtk:3:in `<main>'
	1: from /home/bina/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/bina/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- gtk3 (LoadError)
```
`gem` is a package system for ruby to install ruby libs to use it and `gtk3` is a gem (libs) which have to be installed. So you need only to call `gem install gtk3` like down in the shell output. The tool `apt` not needed. 
```
bina@debianbina:~/code/homebank-gtk-app$ gem install gtk3
Fetching: gtk3-3.3.6.gem (100%)
Building native extensions. This could take a while...
Successfully installed gtk3-3.3.6
Parsing documentation for gtk3-3.3.6
Installing ri documentation for gtk3-3.3.6
Done installing documentation for gtk3 after 0 seconds
1 gem installed

```

**Comment by sabinahofmann** [comment]
Did it work?

**Comment by MitraMai** [comment]
Ah, I didn't get that "gem" is a Ruby-command. Thought it was a packade :) I'll test it tomorrow

**Comment by MitraMai** [comment]
Hmm... Tried it out right now. I get this error:
```
[martin@MegaCityOne homebank-gtk-app-master]$sudo gem install gtk3
Building native extensions. This could take a while...
ERROR:  Error installing gtk3:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/glib2-3.3.6/ext/glib2
/usr/bin/ruby2.5 -r ./siteconf20190330-13339-ojhmsy.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/glib2-3.3.6 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/glib2-3.3.6/gem_make.out

```

**Comment by sabinahofmann** [comment]
I just tried to run ruby on ubunutu 18.04.2 LTS.
The best way to install ruby is over rvm. Here are the steps you need to do (for more information please look at this site https://linuxize.com/post/how-to-install-ruby-on-ubuntu-18-04/ paragraph "Install Ruby using RVM"):

First you have to download the code from github under your prefer directory for example:
/home/userXXX/code/homebank-gtk-app.
Seconds you need update packages and install rvm. After this you can install ruby and gtk3 (please note do not change your prefer directory). 
 ```
$ sudo apt update
$ sudo apt install curl g++, gcc, autoconf, automake, bison, libc6-dev, libffi-dev, libgdbm-dev, libncurses5-dev, libsqlite3-dev, libtool, libyaml-dev, make, pkg-config, sqlite3, zlib1g-dev, libgmp-dev, libreadline-dev, libssl-dev
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
$ curl -sSL https://get.rvm.io | bash -s stable
$ source ~/.rvm/scripts/rvm
$ rvm install 2.5.1
$ rvm use 2.5.1 --default
$ ruby -v
Output: ruby 2.5.1p57 (...)
$ gem install gtk3
$ ./homebank-gtk
```

**Comment by sabinahofmann** [comment]
Can I close the issue?

**Comment by sabinahofmann** [comment]
will be closed, no further reponse to my request
